kind: pipeline
type: docker
name: cthunline-games-ci

# when to execute pipeline
trigger:
  branch:
  - master
  - dev
  event:
  - push
  - pull_request

steps:
# install dependencies
- name: install
  image: node:16-alpine
  pull: if-not-exists
  commands:
  - npm i
# linters
- name: lint
  image: node:16-alpine
  pull: if-not-exists
  commands:
  - npm run lint
  depends_on:
  - install

---
kind: pipeline
type: docker
name: cthunline-games-cd

# when to execute pipeline
trigger:
  event:
  - tag

# publish to npm
steps:
- name: npm  
  image: plugins/npm
  settings:
    username:
      from_secret: npm_user
    token:
      from_secret: npm_user
