steps:
- name: install
  image: node:22-alpine
  pull: true
  commands:
  - npm i
  when:
    branch:
    - master
    event:
    - push
    - pull_request
- name: lint
  image: node:22-alpine
  pull: true
  commands:
  - npm run lint
  depends_on:
  - install
  when:
    branch:
    - master
    event:
    - push
    - pull_request
